version: "3.9"

services:
 multiversx:
  image: multiversx/chainsimulator:v1.7.12-fix1
  ports:
    - 8085:8085
  volumes:
    - "../scripts:/docker/scripts"
  # TODO: revert
  entrypoint: "./chainsimulator -log-level *:DEBUG,process:TRACE,vm:TRACE -log-save"
