version: "3.9"

services:
  sc-calls-executor:
    build:
      context: ..
      dockerfile: scCallsExecutor.Dockerfile
    restart: unless-stopped
    volumes:
      - "../keys:/klever/keys"
    # change the `network-address`, `sc-proxy-address` and `private-key-file` accordingly
    entrypoint: "./scCallsExecutor \
    -log-level *:DEBUG \
    -log-save \
    -network-address https://node.devnet.klever.org \
    -sc-proxy-address klv1qqqqqqqqqqqqqpgqu2jcktadaq8mmytwglc704yfv7rezv5usg8sgzuah3 \
    -private-key-file ./keys/walletKey.pem"
