name: Build

on:
  push:
    branches: [ main, feat/* ]
  pull_request:
      branches: [ main, feat/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Go Setup
        uses: ./.github/actions/go-setup-action
        with:
          go-version: ${{vars.GO_VERSION }}
          go-private: ${{vars.GO_PRIVATE_REPO }}
          git-user: ${{ secrets.GIT_USER }}
          git-pass: ${{ secrets.GIT_PASS }}

      - name: Build
        run: |
          cd ${GITHUB_WORKSPACE}/cmd/bridge && go build .
