name: Tests

on:
  push:
    branches: [ main, feat/* ]
  pull_request:
    branches: [ main, feat/* ]

jobs:
  test:
    name: Unit & Integration
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Go Setup
        uses: ./.github/actions/go-setup-action
        with:
          go-version: ${{ vars.GO_VERSION }}
          go-private: ${{ vars.GO_PRIVATE_REPO }}
          git-user: ${{ secrets.GIT_USER }}
          git-pass: ${{ secrets.GIT_PASS }}

      - name: Unit tests
        run: make test
